// <auto-generated />
namespace LeAn_2011063130.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class KhoiTaoBang : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KhoiTaoBang));
        
        string IMigrationMetadata.Id
        {
            get { return "202303251654376_Khoi Tao Bang"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
